# Generated by Django 5.0 on 2023-12-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmriMbiemri', models.CharField(max_length=1000)),
                ('NumriTelefonit', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=1000)),
                ('Pytja', models.CharField(max_length=1000)),
                ('Ju_kam_Pergjigjur', models.BooleanField()),
            ],
        ),
    ]
