# Generated by Django 5.0 on 2023-12-19 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pytje_ju_kam_pergjigjur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Njoftime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulli', models.CharField(max_length=1000)),
                ('Teksti', models.CharField(max_length=100000)),
                ('Foto', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
                ('Data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
