# Generated by Django 5.0 on 2024-01-02 21:15

import datetime
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_njoftime_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emri', models.CharField(max_length=10000)),
                ('Data', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 22, 15, 17, 966014))),
                ('Video_Youtube', embed_video.fields.EmbedVideoField(blank=True, default=' ')),
            ],
        ),
        migrations.AlterField(
            model_name='njoftime',
            name='Data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 22, 15, 17, 966014)),
        ),
    ]
